language: node_js
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '11'
jobs:
  include:
    - stage: test
      script:
        - node --version
        - yarn --version
        - yarn test
